/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wlopera' at '11/10/16 12:17 PM' with Gradle 2.14.1
 *
 * @author wlopera, @date 11/10/16 12:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
